### ISSUE TITLE
OpenLyrics: Ütemvonal

### ISSUE THREAD

**Issue by gyuris** [gyuris/aszaf#11]
> Ez előjátéknál hasznos lehet az ütemvonal pl. így:
> | A A+ D | E |

Valóban, Laci is kérte, hogy lehetőleg legyen. Ezt szemantikusan egy ütemjelzéssel lehet leírni legtisztábban. Attól függően, hogy végül az akkordokat a szövegre írjuk, vagy hagyományosan két módon is lehetne specifikálni `beat`:

Hagyományos módon:

``` xml
<line>
  <chord name="A" /><chord name="A+" /><chord name="D" /><beat /><chord name="E"><beat />
</line>
```

Szemantikusabban, mely jelzi, hogy az ütem mit foglal magába:

``` xml
<line>
  <beat><chord name="A" /><chord name="A+" /><chord name="D" /></beat>
  <beat><chord name="E"></beat>
</line>
```

Ha ezt kiegészítjük a #10-ben jelzett  `duration` attribútummal az akkordra is, akkor azt is el tudjuk érni, hogy bizonyos akkordok után szünet legyen.

``` xml
<chord name="A" duration="2" /><chord name="A+" />
```

**Comment by triszterer** [comment]
A duration nekem feleslegesnek tűnik. Ha kettő kell egy akkordból, akkor azt kétszer kiijuk. Pl. A A

Viszont, ha lesz ütemvonalunk, akkor az üres akkordra is szükség lehet.

Az általam megadott előjáték helyesen így lenne:
```xml
<line>
  <chord name="-" /><chord name="A" /><chord name="A+" /><chord name="D" /><beat /><chord name="E"><beat />
</line>

| - A A+ D | E |
```
Az első ütemre nincs akkord.

Itt lehet, hogy elég lenne a `name` attributumra a `-` értéket engedélyezni.

A `<beat/>` megoldás alapvetően megfelel, azonban óvaintenék attól, hogy mindent teljes reszletességgel XML-el próbáljuk leírni. Nem lenne célszerű kottát írni XML-ben, illetve ez a fajta szöveges-akkordos énekes "kotta" sem teljesen ekzakt leírási forma.

Anno volt egy javaslatom `<chordtext text="valami">`, ami szinten megoldja az ütemvonal hiányának problémáját és univerzálisan lehetővé teszi, hogy az akkordok közé bármilyen jelet, szöveget elhelyezzünk.

**Comment by gyuris** [comment]
*  „A `duration` felesleges, mert kétszer kiírjuk:” OK. Jó meglátás!
* „Nem lenne célszerű kottát írni XML-ben”: Nagyon is egyetértek! Csak addig menjünk el, amíg az „énekszöveg akkordozva” műfaj terjed, de azt ölelje fel teljes egészében. A kottaírásra már van más: a LilyPond, ill. XML-t tekintve inkább a [MusicXML](http://www.musicxml.com/): ez 100× bonyolultabb és részletesebb, mint az OpenLyrics, érdemes megnézni az [akkordleírását](http://www.musicxml.com/UserManuals/MusicXML/MusicXML.htm#TutMusicXML6-1.htm%3FTocPath%3DMusicXML%25203.0%2520Tutorial|_____7). Durva!
* Üres hely: a `<chord name="-" />` helyett javaslom a #10-ben már említett szünetjelzést: `<rest />`. Így univerzálisabb, egyszerűbb, és illeszkedik a [MusicXML](http://www.musicxml.com/UserManuals/MusicXML/MusicXML.htm#CT-MusicXML-rest.htm)-hez is.

A `<beat />` megjelenítéséről egy szó: Nagyon egyszerű lesz:
```css
beat::after { content: "|" }
```

**Comment by gyuris** [comment]
Lezárom ezt ennek a javára: openlyrics/openlyrics#36.
