### ISSUE TITLE
OpenLyrics: downgrade szkript

### ISSUE THREAD

**Issue by gyuris** [gyuris/aszaf#12]
Ahogy nézegetem a #8, #9, #10, #11 bejegyzéseket és a beszélgetésünket, különösen [ezt](https://github.com/gyuris/aszaf/issues/10#issuecomment-147651928), támadt egy korszakalkotó :-) zseniális ötletem: készítsünk egy downgrade szkriptet, amely a 0.8-as szabványra alakítja vissza az állományainkat. Így végre megszabadulunk attól a kínzó problémától, hogy szép-szép minden ötletünk, csak nem fog együttműködni a nem saját programokkal, ezért nem azt csináljuk, ami kellene, hanem ami belefér.

Szóval, készülhet ez DOM manipulációval, lehet szintén NodeJS-ben, vagy készülhet XSLT-es átalakítással (talán ez a legszebb, de az XSLT-vel sohasem jutottam túl az ismerkedési szinten) is. A lényeg:
- az előjáték, közjáték, utójáték egyszerűen törlődik vagy már ismert versszaktípussá alakul (#8),
- a versszakon belüli ismétlések olyanná alakulnak, ahogy most is vannak, sima szöveggé (#9),
- a szövegre írt akkordok simává lesznek: pl. `<chord name="A">Még nem is éltem én</chord>`→ `<chord name="A" />Még nem is éltem én`. Ide értve a #10 összes módosítását (szünetjel, felütés, hossz attribútum), amiben majd megállapodunk.
- az ütemvonal törlésre kerül (#11)

A helyes irány szerintem az, hogy olyan leírónyelvünk legyen, amelyben mindent meg lehet csinálni, amire szükségünk van. A „butább” programoknak pedig lesz egy visszabutított verzió, amivel nem kell foglalkozni, a build szkript legyártja és nagyszerű. Lehet betolni OpenLP-be, vagy amibe kell.

**Comment by triszterer** [comment]
Nos, valóban. A definciós kérdések egyszerűsödnének, de ennek azért ára van.
* Kell egy konverter (downgrade script)
* Nem tudjuk a már létező OpenLyrics dal szerkesztő programokat használni. Valami sajátot kell készíteni.

Mielőtt erre az útra lépünk megvizsgálnám, hogy valóban nem tudjuk-e, komptibilis módon kiegészíteni az OpenLyrics szabványt, hogy az igényeinknek megfeleljen. Én a definiciós kérdéseknél nem látok megoldhatatlan problémákat. A megjelenitési (implementációs) kérdéseket sajnos ez sem fogja megoldani.

**Két javaslat:**
* Gyüjtsük össze mégegyszer, hogy pontosan mire is van szükségünk definicós szinten és nézzük meg, hogy valóban nem lehet megfelelő módón megoldani OpenLyrics alatt.
* Tovább gondolva az ötletedet, még azon lehetne eltűnődni, hogy nincs-e egy másik szabvány, ami az igényeinknek jobban megfelel. Mert ha lenne, akkor vélhetően tool-ok is vannak hozzá. Igy könnyebb szívvel tudnám ezt a lépést meglépni.
  * Érdemes lenne megvizsgálni [ChordPro formátumot] (https://linkesoft.com/songbook/chordproformat.html). Ez elég egyszerű. Emlékeim szerint telefonos appok is vannak hozzá.

**Comment by gyuris** [comment]
Néhány év eltelt, de a 0.9-tól 0.8-ra konvertáló XSLT elkészült:
- XSLT: https://github.com/gyuris/openlyrics-prototype/blob/master/tools/openlyrics-0.9-to-openlyrics-0.8.xsl
- A meghívása: https://github.com/gyuris/openlyrics-prototype/blob/master/tools/openlyrics-0.9-to-openlyrics-0.8.xsl

Érintett véglegesítések:
- https://github.com/gyuris/openlyrics-prototype/commit/c1864c44d42f43ed5cb36746c25df623c1eb203b
- https://github.com/gyuris/openlyrics-prototype/commit/54c23be35f3996e9c5fafd71fa26c161554e1562
