### ISSUE TITLE
Átrendezés a master mappába

### ISSUE THREAD

**Issue by gyuris** [gyuris/aszaf#13]
A [refactor-build](/gyuris/aszaf/tree/refactor-build) branch-ben már a Sárga könyvet (akkord nélküli) és a Szent András Énekfüzet átmozgattam, közben ügyelve a duplikátumokra (volt egy fájlütközés, és egy közös dal: Világosságot küldd el).

Tamás, megteszed ezt azokkal a gyűjteményekkel, amelyeket te hoztál a repóba?

Ha ezzel megvagyunk, akkor lehet a branchet beolvasztani a fő ágba és kiadást csinálni. Addig mást nem nagyon kellene fejleszteni.

**Comment by triszterer** [comment]
Ok. Félek, hogy csak hétvégén tudok majd vele foglalkozni...

**Addig is egy kérdés:**
A DiaTárból sok különféle dolog át lett hozva. Zsoltárok, zsolozsma, mise szövegek, latin imák stb. Nem gondolnám, hogy ezeket is át kellene mozgatni master-ba. Véleményem szerint, csak a gitáros énekeket kellene a master-ba rakni. Szóval csak a Kék könyv, a Zöld könyv és esetleg a Taize énekeket tenném át.

Azok az anyagok, amiket nem teszünk a master-ba, azok megmaradnának az eredeti formában GitHub-on.

Mit gondolsz?

**Comment by gyuris** [comment]
Hétvége tökéletes.

DiaTár és gitáros énekek: Egyetértek. Ne vegyünk mindent a hátunkra. 

Javaslom, hogy az összes hagyományos vagy klasszikus egyházi éneket és más imaszövegeket tegyük egy másik mappába (`other, classical, ?`) így ahogy most vannak gyűjteményekre bontva. Ezeket ugyanis nem nagyon akarjuk bolygatni. Jó, hogy vannak, lehet használni őket. Innentől kezdve két dolog tudok elképzelni:

1. Írok rá egy másik build szkriptet a mostani alapján, amely csinál belőlük letölthető állományt és tartalomjegyzéket
2. Vagy csak simán natúrban kézzel összedobjuk a 7z-be tömörített állományt (tartalomjegyzék nélkül) és betesszük a gyökérbe. Ha néhanapján van ezekhez javítás, akkor ezt megismételjük kézzel.

Szerintem a 2. megoldás elég. :-)

**Comment by triszterer** [comment]
OK

**Comment by gyuris** [comment]
Ok, akkor az átrendezés ezennel 14c90eade73dd40cb7c07d7c071bc4b60b476f7 kész és be van olvasztva a fő ágba.
