### ISSUE TITLE
OpenLyrics: CSS hivatkozás

### ISSUE THREAD

**Issue by gyuris** [gyuris/aszaf#14]
Jó lenne ha a úgy tudnánk elmenteni a `master`-be a OpenLyrics állományokat, hogy azokba beletennénk a CSS fájlra való hivatkozást. Vagyis ez azt jelenti, hogy egyből meg lehetne nézni az állományt, könnyű ellenőrizni, ha valami hibás, nem jól sikerült. Kb. így: 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="openlyrics.css" type="text/css"?>
<song xmlns="http://openlyrics.info/namespace/2009/song">
```

Probléma: Ha így próbálom importálni az állományt OpenLP-be, akkor nem sikerült az import, hibás XML formázásra panaszkodik. Egy downgrade szkript (#12) segíthet ezen, hogy a gyűjteménybe exportáláskor kivegyük a hivatkozást.

**Comment by triszterer** [comment]
1. Szerintem először fejezzük be a dalok importálását a master-ba. 

2. Utána meg kellene beszélni, hogy milyen formátumban legyenek az énekek tárolva:
 * Kibővített OpenLyrics formátum
 * Saját XML formátum
 * Esetleg kibővitett ChordPro formátum

3. Majd, átkonvertáljuk az énekeket az új formátumba.

Végül ezen ponton kellene eltűnődni azon, hogy mi legyen a CSS hivatkozással, illetve milyen konvertáló script-ek kellenek.

**Comment by gyuris** [comment]
Itt ezt lezárom ennek a javára: openlyrics/openlyrics#31
