### ISSUE TITLE
Duplikátum

### ISSUE THREAD

**Issue by gyuris** [gyuris/aszaf#20]
@triszterer, fogtam néhány duplikátumot az OpenLP duplikátumkeresőjével:
```
/master/Kegyelmed, Úr Jézus.xml
/master/Kegyelmed Úr Jézus (ismeretlen szerző).xml

/master/Áldás, méltóság és er.xml
/master/Áldás, méltóság és erő (Leonard Jones, Prazsák László).xml

/master/Laudate Dominum, laudate.xml
/master/Áldjátok az Úrat - Laudate Dominum.xml

/master/Áldott légy nagy jóságodért.xml
/master/Áldott légy nagy jóságodért (ismeretlen szerző).xml

/master/Áldott légy, Uram, szent.xml
/master/Bless the Lord my soul.xml

/master/Bless the Lord my soul.xml
/master/De profundis (A legsötétebb ég alatt).xml

/master/Stabat Mater.xml
/master/Áll a fájdalomnak anyja.xml

/master/Mise III.xml
/master/A mélyből kiáltok (Sillye Jenő).xml
/master/Mise III.xml
/master/Dicsőség.xml
/master/Szent vagy.xml
/master/Mise III.xml
? /master/Isten Báránya, Te elveszed.xml
? /master/Mise III.xml vagy
? /master/Mise IV.xml

/master/Mise IV.xml
/master/Uram, irgalmazz.xml
/master/Mise IV.xml
/master/Dicsőség a magasságban.xml

/master/Anyánk az égben.xml
/master/Anyánk vagy az égben.xml

/master/Apokrif ima.xml
/master/Apokrif ima.xml

/master/Jézus Király.xml
/master/Jézus Király.xml

/master/Édes Jézus (2).xml
/master/Édes Jézus, légy vendégünk.xml

/master/Szeretem örökké.xml
/master/Eléd lépek, jó Uram, hol béke.xml

? /master/Én Uram, én Istenem (DAX, Fülei Szt. Miklós).xml
? /master/Ti vagytok a Föld sója (Én Uram, én Istenem).xml

/master/Mária édesanyám, Béke.xml
/master/Gospa májká mojá.xml

/master/Fogadd el Uram (ismeretlen szerző).xml
/master/Fogadd el, Uram (Tolcsvai László).xml

/master/Hála legyen (Isten a szépség).xml
/master/Isten a szépség, Isten a jó.xml

/master/Halld, Izrael.xml
/master/Halld, Izrael (ismeretlen szerző).xml

/master/Hogyha csak egy ((Grupo Nueva Vida), Fábry Kornél).xml
/master/Hogyha csak mustármagnyi.xml

/master/Mise.xml
/master/Irgalmazz énnekem, jó Atyám.xml

/master/Isteni béke.xml
/master/Isteni béke, boldog öröm.xml

/master/Jézusom, Jézusom.xml
/master/Jézusom, Jézusom, a gyermeked lettem.xml

/master/Jézus vár terád.xml
/master/Jézus vár terád (ismeretlen szerző).xml

/master/Jöjj, itt az idő (Brian Doerksen, (Golgota Debrecen), Csiszér László szövegvariánsa).xml ) [ez a szövegvariáns kerüljön be!]
/master/Jöjj, itt az idő, hogy ébredj.xml

/master/Légy hideg vagy légy meleg.xml
/master/Válasszál.xml

/master/Megszülettem (Máriáss Péter).xml
/master/Megszülettem, Te adtad életem.xml

/master/Mentsd meg a lelkem.xml
/master/Tisztítsd meg szemem (ismeretlen szerző).xml
[eltérő szöveg, a kék könyv szövegvariánsa a megbízhatóbb általában]

/master/Tisztítsd meg szemem (ismeretlen szerző).xml
/master/Totus tuus.xml

/master/Nap, hold, csillagok (ismeretlen szerző).xml
/master/Szeretünk Téged, Mária.xml

/master/Ó drága Jézusunk.xml
/master/Ó, drága Jézusunk, jóságod.xml

/master/Ó Jézus, a Te lényed.xml
/master/Ó, Jézus, a Te lényed (Csiszér László).xml

/master/Szentlélek jöjj.xml
/master/Szentlélek jöjj, szállj le rám (Csiszér László).xml

/master/Szentlélek, jöjj, lobogó Láng.xml
/master/Szentlélek, jöjj, lobogó Láng (J-M. Morin, Fábry Kornél).xml

/master/Szentlélek, úgy kérünk.xml
/master/Szentlélek, úgy kérünk (Varga Attila).xml

/master/Szent, szent a neve.xml
/master/Szent, szent a neve (Viszmeg László, Viszmeg Viola).xml

/master/Szent vagy, szent vagy, szent.xml
/master/Szent vagy… Jahve Sabaoth (Kiko Argüello, Csiszér László).xml

/master/Szeretet áradjon.xml
/master/Szeretet áradjon (ismeretlen szerző).xml

/master/Tárd ki a karod, emeld fel.xml
/master/Tárd ki karod.xml

? /master/Üdvözlégy, Mária (ismeretlen szerző).xml
? /master/Üdvözlégy Mária, malaszttal (Hollósy Péter).xml
```
Ezek nem duplikátumok, de szerintem összevonandók:
```
/master/Kanadai mise - Alleluja.xml
/master/Kanadai mise - Kyrie.xml
/master/Kanadai mise - Sanctus.xml
```

Utána nézel ezeknek? Ha szerinted is duplikátumok, kérlek egyesítsd őket ügyelve a szerzőkre, alcímekre, könyvekre. 

Kérlek, dalonként kommitold (ne ömlesztve), hogy követhető legyen mi történik.

És ha ezzel megvagy, újra importáljuk be az összeset és újra futtassuk le. :-) Jó kis cucc.

**Comment by triszterer** [comment]
**Commitolva.**

Ami még hiányzik:
```
/master/Mise III.xml
/master/A mélyből kiáltok (Sillye Jenő).xml
/master/Mise III.xml
/master/Dicsőség.xml
/master/Szent vagy.xml
/master/Mise III.xml
? /master/Isten Báránya, Te elveszed.xml
? /master/Mise III.xml vagy
? /master/Mise IV.xml

/master/Mise IV.xml
/master/Uram, irgalmazz.xml
/master/Mise IV.xml
/master/Dicsőség a magasságban.xml
```
Szerintem nem kellene összevonni őket. Van hogy szemezget az ember: Egy kis dicsőség innen, uram irgalmazz onnan... Jobb ha külön-külön is ki lehet vetíteni őket.
```
/master/Kanadai mise - Alleluja.xml
/master/Kanadai mise - Kyrie.xml
/master/Kanadai mise - Sanctus.xml
```

**Comment by gyuris** [comment]
Szia!
Köszi. Egy pull-t is légy szíves, hogy felkerüljön.
G.

2016-01-27 10:42 keltezéssel, triszterer írta:
>
> *Commitolva.*
>
> Ami még hiányzik:
>
> |/master/Mise III.xml /master/A mélyből kiáltok (Sillye Jenő).xml 
> /master/Mise III.xml /master/Dicsőség.xml /master/Szent vagy.xml 
> /master/Mise III.xml ? /master/Isten Báránya, Te elveszed.xml ? 
> /master/Mise III.xml vagy ? /master/Mise IV.xml /master/Mise IV.xml 
> /master/Uram, irgalmazz.xml /master/Mise IV.xml /master/Dicsőség a 
> magasságban.xml |
>
> Szerintem nem kellene összevonni őket. Van hogy szemezget az ember: 
> Egy kis dicsőség innen, uram irgalmazz onnan... Jobb ha külön-külön is 
> ki lehet vetíteni őket.
>
> |/master/Kanadai mise - Alleluja.xml /master/Kanadai mise - Kyrie.xml 
> /master/Kanadai mise - Sanctus.xml |

-- 
Gyuris Gellért
H-6724 Szeged, Rigó u. 16/A TT8
+3630 3808472 bubu@ujevangelizacio.hu
http://bubu.ujevangelizacio.hu

**Comment by triszterer** [comment]
Hátha elfeljetettem volna egy pull-t nyomni, akkor azt csak munka után
otthon tudom megtenni.

Tamás
2016.01.27. 10:48 ezt írta ("Gyuris Gellért" <notifications@github.com>):

**Comment by triszterer** [comment]
Szia Gellért!

Elméletileg minden fent van (refactor-build).

Tamás
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Ezt
az e-mailt egy Avast védelemmel rendelkező, vírusmentes számítógépről
küldték.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-27 10:48 GMT+01:00 Gyuris Gellért <notifications@github.com>:

**Comment by gyuris** [comment]
Ok, akkor ez beolvasztva a fő ágba. Köszönöm, szép munka!

Kérlek, hogy állítsd át magadnál is át a master ágba a tárolót. A rafactor-build ágat ezzel azt hiszem egyelőre lezárhatjuk. 

Holnap reggel hoznak neked egy Kék könyvet, a https://github.com/gyuris/aszaf/issues/20#issuecomment-175513614 hozzászólásban jelzett maradékot feldolgozom. Aztán tesztelem, hogy maradt-e még duplikátum.

**Comment by triszterer** [comment]
Ok. Koszi.
Tamás
2016.01.27. 21:31 ezt írta ("Gyuris Gellért" <notifications@github.com>):

**Comment by gyuris** [comment]
Akkor ezzel készen vagyunk. Még egyszer ellenőriztem az OpenLP „Duplikált dalok keresése” funkcióval. Találtam még néhány duplikátumot, ezek javítása be lett ide hivatkozva a változásokkal.
